version: 0.2

phases:
  install:
    commands:
      # upgrade the version of node.js
      - node -v
      # using node v18
      - n 18
      - node -v
      - echo "Installing dependencies..."
      # cd root dir
      - cd eks-test
      # install dependencies
      - npm install # or any other package manager command
  
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})

  build:
    commands:
      - docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG} .
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG}

  post_build:
    commands:
      - echo "Running post-build actions..."

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
