version: 0.2

phases:
  install:
    commands:
      - node -v
      - n 18
      - node -v
      - echo "Installing dependencies..."
      - cd eks-test
      - npm install # or any other package manager command

  build:
    commands:
      - echo "Building the application..."
      - nodemon # or any other build command

  post_build:
    commands:
      - echo "Running post-build actions..."

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
