version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - cd githubActions_codeBuild_ecs
      - pip install -r requirements.txt
      - python app_test.py
